[tool.poetry]
name = "cve-exposure"
version = "0.1.0"
description = "Web scraper that looks for CVEs that are actively discussed from a curated list of news sources."
authors = ["lafiamafia <lafiamafia@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
